server:
  port: 8084

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user_service/**
        - id: user-menu
          uri: lb://USER-MENU
          predicates:
            - Path=/user_menu/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
